apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressuploader
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: expressuploader
  template:
    metadata:
      labels:
        app: expressuploader
    spec:
      containers:
      - name: expressuploader
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: DESTINATION_PATH
          value: "/mnt/storage"
        volumeMounts:
        - name: expressuploader-storage
          mountPath: /mnt/storage
      volumes:
      - name: expressuploader-storage
        persistentVolumeClaim:
          claimName: expressuploader-pvc
