apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expressuploader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
