replicaCount: 1
image:
  repository: idjohnson/expressuploader
  tag: latest
  pullPolicy: IfNotPresent
  # pullSecret: secret with credentials for private registry
service:
  type: ClusterIP
  port: 80
zipkinEndpoint: http://localhost:9411
pvc:
  accessModes:
    - ReadWriteOnce
  storage: 5Gi
  storageClassName: "local-path"
